In [ ]:
tup1 = (1,2,3,4,5)
li = list(tup1)
print(type(li))

<class 'list'>


In [ ]:
tup = (1,2,3,4)
li = list(tup)
type(li)
li.pop(2)
tup = (tuple(li))
print(tup)

(1, 2, 4)


In [ ]:
a = 2
b = 4
print(a+b,a-b,a%b,a/b,a*b,a//b,a**b)

17 -3 7 0.7 70 0 282475249


In [ ]:
print(a//b)

0


In [ ]:
a = 2
b = 4
a**b

16

In [ ]:
a*a*a*a

16

In [ ]:
y = 2
x = 4
x%y 

0

In [ ]:
c = 36 
d = 8
c%d

4

In [ ]:
x = 10
y = 10
x > y or y > x


False

In [ ]:
x != y

False

In [ ]:
 a= 16
 b = 16
 print(a>b)
 print(a<b)
 print(a>=b)
 print(a<=b)
 print(a==b)
 print(a!=b)
 

False
False
True
True
True
False


In [ ]:
a>=b, a<=b

(True, True)

In [ ]:
y = 5
y+=3
print(y)
y-=4
print(y)
y /=5
print(y)

8


In [ ]:
x = 3
x >>=3
print(x)

0


In [ ]:
 print("This is liza's bag")

This is liza's bag


In [ ]:
###Data types

x = 26 # integer becoz it is a whole number
y = 23.55 # float - becoz it has decimal values
z = True/False #boolean values
a = "text" #string - textual values
1,2,3,4,5,5,6,7,6,3,4
(1,2,3,4,5,6,7) - #set
complex - 5 + 3i 

Sequences, - List[] and Tuple()

list is modifiable, tuple is not
List can be converted to tuple and viceversa



In [ ]:
x= 23
y=23.5
z = 5j
print(type(x))
print(type(y))
print(type(z))

<class 'int'>
<class 'float'>
<class 'complex'>


In [ ]:
#List 
a= [10,20,30,40]
print(type(a))

<class 'list'>


In [ ]:
a = [10]
a

[10]

In [ ]:
#list.append - append can add only 1 value at a time, accepts the duplicates n number of times
a.append(20)
print(a)

NameError: ignored

In [ ]:
#format Specifier
name = 'Soham'
print("My name is %s" %name)

My name is Soham


In [ ]:
name = "John"
age = 23
print("%s is %d years old." % (name, age))

John is 23 years old.


In [ ]:
b = [20,30,40]
b.insert(3,40)
print(b)


[20, 30, 40, 40]


In [ ]:
b = [20,30,40]
b.extend([110])
print(b)

[20, 30, 40, 110]


In [ ]:
b = [20,30,40]
b.remove(20)
print(b)

[30, 40]


In [ ]:
b = [20,30,40]
b.clear()
print(b)
#clear function clears the entire list and not any specified values

[]


In [ ]:
b = [20,30,40]
del b
print(b)
#del can delete entire list and not print anything, also it can delete specific value

NameError: ignored

In [ ]:
b = [20,30,40]
b.pop()
print(b)
#pop deletes last item if no value is provided, and it deletes the index value in the list

[20, 30]


In [ ]:
#indexing and slicing
l1 = [1,2,3,4,5,6,7,8,9]
print(l1[2])

3


In [ ]:
l1 = [1,2,3,4,5,6,7,8,9]
print(l1[-1:-6:2])
#negative index starts with -1, 
#(initialindex, end index(will exclude), jump index)
##Pull 1 and 5 from the list above using negative indexing.

[]


In [ ]:
l1 = [1,2,3,4,5,6,7,8,9]
print(l1[-9:6:4]) 
##-9 = starting point, -4 = end point is always excluded, 4 = jumping index
#initial = 0,-9
#final = 8,-4
#increment/jump index =4
#index counts from left to right
#--------->>>>>

[1, 5]


In [ ]:
#print 3 and 8 using negative index
l1 = [1,2,3,4,5,6,7,8,9]
print(l1[-7:-3:2])

[3, 5]


In [ ]:
##tuple - we can only index and slice a tuple, no other functions are validated
l1 = (1,2,3,4)
print(type(l1))

<class 'tuple'>


In [ ]:
# appending tuples
l2 = list(l1)
print(type(l2))

<class 'list'>


In [ ]:
l2.append(3)
l2

[1, 2, 3, 4, 3, 3, 3]

In [ ]:
l2 = tuple(l2)
print(type(l2))

<class 'tuple'>


In [ ]:
l2
#type casting - convert one data type to another 

(1, 2, 3, 4, 3, 3, 3)

In [ ]:
l1 = (1,2,3,4)
print(type(l1))
l2 = list(l1)
l2.append(4)
print(l2)
print(type(l2))
l1 = tuple(l2)
print(l1)
print(type(l1))

<class 'tuple'>
[1, 2, 3, 4, 4]
<class 'list'>
(1, 2, 3, 4, 4)
<class 'tuple'>


In [ ]:
###A Set is an unordered collection of data type that is iterable.
#It is mutable and has no duplicate elements .
#The order of elements in a set is undefined.
#Items of a set are separated by commas and are enclosed within curly brackets { }.
#Unlike other collections in Python, there is no index attached to the elements of the set, i.e., we cannot directly
#access any element of the set by the index.

In [ ]:
Set1 = {1,2,3,4,5,6,7,0,20,399,23,26,3999}
print(Set1)

{0, 1, 2, 3, 4, 5, 6, 7, 399, 20, 23, 26, 3999}


In [ ]:
s1 = {1,12,31,40,500,2,89,8,9,0,'soham',24.55}
s1.add(2000)
s1

{0, 1, 12, 2, 2000, 24.55, 31, 40, 500, 8, 89, 9, 'soham'}

In [ ]:
thisset = {"apple", "banana", "cherry"}
tropical = {"pineapple", "mango", "papaya"}

thisset.update(tropical)

print(thisset)

{'papaya', 'pineapple', 'apple', 'banana', 'cherry', 'mango'}


In [ ]:
## update any iterable object

thisset = {"apple", "banana", "cherry"}
mylist = ["kiwi", "orange","banana"]

thisset.update(mylist)

print(thisset)

{'kiwi', 'banana', 'apple', 'cherry', 'orange'}


In [ ]:
## remove() and discard() can be used to remove the item in the set
##  If the item to remove does not exist, discard() will NOT raise an error.
## If the item to remove does not exist, remove() will raise an error.
## Sets are unordered, so when using the pop() method, you do not know which item that gets removed.

thisset = {"apple","banana","kiwi", "orange", "cherry"}
thisset.discard("banana")
print(thisset)


{'apple', 'cherry'}


In [ ]:
set1 = {"apple","banana","kiwi", "orange", "cherry"}
set1.pop()
print(set1)

{'banana', 'apple', 'cherry', 'orange'}


In [ ]:
set1 = {"apple","banana","kiwi", "orange", "cherry"}
set1.pop()
print(set1)
set1

{'banana', 'apple', 'cherry', 'orange'}


{'apple', 'banana', 'cherry', 'orange'}

In [ ]:
set1 = {"apple","banana","kiwi", "orange", "cherry"}
set1.pop()
print(set1)
set1

{'banana', 'apple', 'cherry', 'orange'}


{'apple', 'banana', 'cherry', 'orange'}

In [ ]:
#The union() method returns a new set with all items from both sets:

set1 = {"a", "b" , "c",2,3}
set2 = {1, 2, 3,4}

#set3 = set1.union(set2)
#print(set3)
##The intersection() method will return a new set, that only contains the items that are present in both sets.
set4 = set1.intersection(set2)
print(set4)
##The intersection_update() method will keep only the items that are present in both sets.
set1.intersection_update(set2)
print(set1)
print(set2)
##This method returns None (meaning it does not have a return value). It only updates the initial set calling the intersection_update() method.

{2, 3}
{2, 3}
{1, 2, 3, 4}


In [ ]:
#The symmetric_difference() method will return a new set, that contains only the elements that are NOT present in both sets.
x = {"apple", "banana", "cherry"}
y = {"google", "microsoft", "apple"}

z = x.difference(y)

print(z)

x = {"apple", "banana", "cherry"}
y = {"google", "microsoft", "apple"}

z = x.symmetric_difference(y)

print(z)

{'banana', 'cherry'}
{'cherry', 'google', 'banana', 'microsoft'}


In [ ]:
l1 = [0,1,2,3,4,5,6,7,8,9]
print(l1[2:8:2]) 

print(l1[7])
 #2,7 print 

[2, 4, 6]
7


In [ ]:
L1 = [1,2,3,4,5,6,7,8,11,21,8,10,9,4]
#print 1, 5 and 11 using negative index
print(L1[-11::4])

## First index is = -11                                                     ### Output [1]
## Here Jump index value is 4 , so now index -11+4 = -7                     ### Output [1,5]
## Next jum index is 4, currently index value = -7, Now index -7+4 = -3     ### Output [1,5,11]

[4, 8, 10]


In [ ]:
L1 = ['P','U','N','E','E','T']
## PRINT P AND T IN THE ABOVE LIST USING POSITIVE INDEX AND NEGATIVE INDEX
# POSITIVE INDEX
print(L1[0:5:4])
#NEGATIVE INDEX
print(L1[-6:-1:4])
print(L1[::5])
#List [Start Index : End INDEX : Jump Index ]

#KETAN bHAI
print(L1[0::5])
print(L1[-6::5])

['P', 'E']
['P', 'E']
['P', 'T']
['P', 'T']
['P', 'T']


In [ ]:
L1 = ['P','U','N','E','E','T']
print(L1[-1:-6:-3])

['T', 'N']


In [ ]:
Dict = {1:'Puneet', 2:'Phavan', 3:'Mehul'}
# 1- puneet
 #2- phavan
 #3- mehul
print(type(Dict))
Dict[4] = 'Soham','Pallav'
Dict[1] = 'replace the value in key 1'
print(Dict)
Dict.pop(4) #removes the key in the dict
print(Dict)
Dict.popitem() ##popitem deletes the last item from the dict
print(Dict)
del Dict["Mehul"] ##deletes the value in the dictionary
print(Dict)

<class 'dict'>
{1: 'replace the value in key 1', 2: 'Phavan', 3: 'Mehul', 4: ('Soham', 'Pallav')}
{1: 'replace the value in key 1', 2: 'Phavan', 3: 'Mehul'}


In [ ]:
Dict = {1:'Puneet', 2:'Phavan', 3:'Mehul'}
print(Dict)
#del Dict[1] 
##deletes the value in the dictionary
#print(Dict)
Dict[4] = 'Soham'
print(Dict)
Dict[5] = 'red'
print(Dict[5:'red'])
Dict.update({"color": "red"})

{1: 'Puneet', 2: 'Phavan', 3: 'Mehul'}
{1: 'Puneet', 2: 'Phavan', 3: 'Mehul', 4: 'Soham'}
{1: 'Puneet', 2: 'Phavan', 3: 'Mehul', 4: 'Soham', 5: 'red'}


In [ ]:
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
del thisdict["model"]
print(thisdict) 

{'brand': 'Ford', 'year': 1964}


In [ ]:
Dict = {1:'Puneet', 2:'Phavan', 3:'Mehul'}
print(Dict)
del Dict["Mehul"]
print(Dict)

{1: 'Puneet', 2: 'Phavan', 3: 'Mehul'}


KeyError: ignored

In [ ]:
Dict = {1:'Puneet', 2:'Phavan', 3:'Mehul'}
print(Dict[1])

Puneet


In [ ]:
DICC={'Key1': 'Value1', 'Key2': 'Value2'}
print(DICC['Key1'])

Value1


In [ ]:
##Conditional Statements
##if condition
a = int(input('Enter a:'))
b = int(input('Enter b:'))
c = int(input("Enter c:"))
#print(a == b)
#print(a>b and a>c)
if b>a and a>c:
    print('a is greater than b and c is lesser than b')
elif a==b:
    print('b is equal to a')
else:
    print('b is greater','c is lesser than a')

Enter a:2
Enter b:3
Enter c:4
b is greater c is lesser than a


In [ ]:
a = int(input('Enter a:'))
b = int(input('Enter b:'))
option = 0
option = int(input("\n1.Addition\n2.Substraction\n3.Multiplication\n4.PowerOf\n5.Rounded Division\n6.Floated Division\n7.Remainder\nEnter your Operation:"))
if option ==1:
    print("Sum of ",a," and ",b," :", a + b)
elif option ==2:
    print("Difference of ",a," and ",b," :", a - b)
elif option ==3:
    print("Product of ",a," and ",b," :", a * b)
elif option == 4:
    print(a," raised to Power of ",b," :", a ** b)
elif option == 5:
    print("Rounded Division of ",a," and ",b," :", a // b)
elif option == 6:
    print("Floated Division of ", a, " and ", b, " :", a / b)
elif option == 7:
    print("Remainder of Division:", a / b)
else:
    print("Invalid Option")

Enter a:3
Enter b:4

1.Addition
2.Substraction
3.Multiplication
4.PowerOf
5.Rounded Division
6.Floated Division
7.Remainder
Enter your Operation:8
Invalid Option


In [ ]:
num = float(input('Enter a number:'))
if num >= 0:
    if num == 0:
        print ('Inputed Number is Zero.')
    else:
        print ('Inputed Number is Positive Number.')
else:
    print ('Inputed Number is Negative Number.')

Enter a number:1
Inputed Number is Positive Number.


In [ ]:
a = int(input('Enter the number:'))
i = 1
while(i<10):
    print(a, ' * ', i, ' = ',a * i)
    i = i + 1

Enter the number:12
12  *  1  =  12
12  *  2  =  24
12  *  3  =  36
12  *  4  =  48
12  *  5  =  60
12  *  6  =  72
12  *  7  =  84
12  *  8  =  96
12  *  9  =  108


In [ ]:
number=int(input("Enter any number :"))
#store a copy of this number
temp=number
#calculate reverse of this number
reverse_num=0
while(number>0):
    #extract last digit of this number
    digit=number%10
    #append this digit in reveresed number
    reverse_num=reverse_num*10+digit
    #floor divide the number leave out the last digit from number
    number=number//10
#compare reverse to original number
if(temp==reverse_num):
    print("The number is palindrome!")
else:
    print("Not a palindrome!")

Enter any number :22
The number is palindrome!


In [ ]:
number=input("Enter any number :")
i=0
for i in range(len(number)):
    if number[i]!=number[-1-i]:
        print('It is not a palindrome')
        break
    else:
        print('It is a palindrome')
        break

Enter any number :33
It is a palindrome


In [ ]:
number=input("Enter any name :")
i=0
for i in range(len(name)):
    if name[i]!=name[-1-i]:
        print('It is a palindrome')
        break
    else:
        print('It is not a palindrome')
        break

Enter any name :nitin
It is a palindrome


In [ ]:

x = input("Enter any name :")
y = x[::-1]

if (x == y):
 print ('Palindrome')
else:
 print ('Not a palindrome') 


Enter any name :dpak
Not


In [ ]:
i = 1
print('[')
while (i<10):
     i = i+1
    print(i,',', end=' ')
    
print(i,']') 

[
1 , 2 , 3 , 4 , 5 , 6 , 7 , 8 , 9 , 10 ]


In [ ]:
i = 1
while (i<10):
  print(i,',',end=' ')
  i=i+1

1 , 2 , 3 , 4 , 5 , 6 , 7 , 8 , 9 , 

In [ ]:
i = 1
print('[',end='')
while (i<=10): 
    if(i == 10):
        print(i,end='')   
    else:
        print(i, end=',')
    i = i+1
print(']') 

[1,2,3,4,5,6,7,8,9,10]


In [ ]:
4%3

1

In [ ]:
x=15
x^=20
x

27

In [ ]:
x = int(input("Enter your Age: "))
y = input("Enter your Gender: ")
if x>=18:
  if y==y.upper() == 'MALE' or y.upper() == 'BOY')):
    print("You are above 18 and %s" %y)
  elif (y.upper() == 'MALE' or y.upper() == 'BOY')):
    print("You are above 18 and %s" %y)
  
else:
    print("You are not")

SyntaxError: ignored

In [ ]:
X = int (input("Print Your Number:"))
Y = int (input("Print Your Number:"))
Z = int (input("Print Your Number:"))

if (X > Y and X > Z) or (Y > X and Y > Z) or (Z > X and Z > Y):
    print("Largest number is %s" %X)
    print("Largest number is %s" %Y)
    print("Largest number is %s" %Z)

Print Your Number:10
Print Your Number:30
Print Your Number:5
Largest number is 10
Largest number is 30
Largest number is 5


In [ ]:
#Program _ Name & age of the User as inputs & display 
name=input("enter the name:")
age=int(input("enter the age:"))
if (age>=18):
 print("eligible for license:")
else:
 print(name,"not eligible for license")

enter the name:dpak
enter the age:19
eligible for license:


In [ ]:
a='dpaknh'
a=set(a)
a

{'a', 'd', 'h', 'k', 'n', 'p'}

In [ ]:
b= 'dhoni'
b=set(b)
b

{'d', 'h', 'i', 'n', 'o'}

In [ ]:
a.union(b)

{'a', 'd', 'h', 'i', 'k', 'n', 'o', 'p'}

In [ ]:
a.intersection(b)

{'d', 'h', 'n'}

In [ ]:
a-b

{'a', 'k', 'p'}

In [ ]:
a and b

{'d', 'h', 'i', 'n', 'o'}

In [ ]:
p={1,2,3,4,5}
sum(p)
p

{1, 2, 3, 4, 5}

In [ ]:
p={1,2,3,4,5}
c= {3,5,6,7,8,9}
d=p.union(c)
d

{1, 2, 3, 4, 5, 6, 7, 8, 9}

In [ ]:
d.issuperset(p)

True

In [ ]:

#Q1. count words and characters in below string
# mainString = 'Data Science 2020 batch'
# HINT : Use split or,  Use for loop + count
str="Data Science 2020 batch"
count=0

for i in str:
  count+=1
count


23

In [ ]:
mainString = 'Data Science 2020 batch'
count=0
for i in mainString:
  count+=1
count

23

In [ ]:
main_string="data science 2020 batch"
rs=len(main_string.split())
print("number of words: ", rs)

number of words:  4


In [ ]:
#Q2. Extract mobile number :
# mainString = 'My number is 8888888888'
# HINT : Use string testing methods + looping

str= 'My number is 8888888888'
rs= str.split()
print('number of word:',rs)
rs[-1]

number of word: ['My', 'number', 'is', '8888888888']


'8888888888'

In [ ]:
str= 'My number is 8888888888'
num=''
for s in str:
  if s.isdigit():
  num=num+s
  else:
    pass
print(num)


IndentationError: ignored

In [ ]:
#Q3. Extract email addresss :
# mainString = 'My email is  abc@g.com'
# HINT : Use string split and membership "in" operator

email= 'My email is  abc@g.com'
sp= email.split()
sp[-1]

'abc@g.com'

In [ ]:
email= 'My email is  abc@g.com'
sp= email.split()
for i in email:
  if @ in i:
    email=i
  else:
    pass
print(email)

SyntaxError: ignored

In [ ]:

# Q4. fibanocci series for 10 numbers
# example : result = 0, 1, 1, 2, 3, 5, 8, 13, 21, 34
A=5
n1, n2 = 0, 1
count = 0

if A <=1:
  print("Fibonacci sequence upto",A,":")
  print(n1)
else:
  # print("Fibonacci sequence:")
   while count < A:
       print(n1)
       nth = n1 + n2
       # update values
       n1 = n2
       n2 = nth
       count += 1

0
1
1
2
3


In [ ]:
A=10
n1, n2 = 0, 1
count = 0
if A <=1:
    print(n1)
else:
   while count < A:
       print(n1)
       nth = n1 + n2
       n1 = n2
       n2 = nth
       count += 1


In [ ]:
import numpy as np

In [ ]:
v= np.linspace(1,5,10)
v

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [ ]:
v_rshp= v.reshape(10,1)

In [ ]:
v_rshp

array([[1.        ],
       [1.44444444],
       [1.88888889],
       [2.33333333],
       [2.77777778],
       [3.22222222],
       [3.66666667],
       [4.11111111],
       [4.55555556],
       [5.        ]])

In [ ]:
v.shape

(10,)

In [ ]:
v= np.random.randint(1,10,size=(5,4))

In [ ]:
v


array([[8, 4, 7, 3],
       [2, 5, 7, 6],
       [1, 9, 7, 6],
       [2, 5, 3, 4],
       [2, 3, 5, 1]])

In [ ]:
v[3]

array([2, 5, 3, 4])

In [ ]:
v.shape

(5, 4)

In [ ]:
n= v.reshape(20,1)

In [ ]:
n

array([[8],
       [4],
       [7],
       [3],
       [2],
       [5],
       [7],
       [6],
       [1],
       [9],
       [7],
       [6],
       [2],
       [5],
       [3],
       [4],
       [2],
       [3],
       [5],
       [1]])

In [ ]:
v

array([[8, 4, 7, 3],
       [2, 5, 7, 6],
       [1, 9, 7, 6],
       [2, 5, 3, 4],
       [2, 3, 5, 1]])

In [ ]:
v[0:,0].reshape(-1,1)

array([[8],
       [2],
       [1],
       [2],
       [2]])

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
a= [5,2,7,4,1]
a

[5, 2, 7, 4, 1]

In [ ]:
type (a)

list

In [ ]:
row_label= ['Zeorth_row','first_row','second_row','third_row','forth_row']

In [ ]:
v= pd.Series(data=a,index= row_label)
v

Zeorth_row    5
first_row     2
second_row    7
third_row     4
forth_row     1
dtype: int64

In [ ]:
b= [8,12,17,14,21]
v1= pd.Series(data=b,index= row_label)
v1

Zeorth_row     8
first_row     12
second_row    17
third_row     14
forth_row     21
dtype: int64

In [ ]:
c= v+v1
c

0    13
1    14
2    24
3    18
4    22
dtype: int64

In [ ]:
type(v)

pandas.core.series.Series